<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="base">

  <xacro:arg name="laser_enabled" default="1" />
  <xacro:arg name="laser_xyz" default="0.2206 0.0 0.00635" />
  <xacro:arg name="laser_rpy" default="0.0 0.0 0.0" />
  <xacro:property name="laser_z_offset" value="0.1" />

  <xacro:arg name="realsense_enabled" default="0" />
  <xacro:arg name="realsense_xyz" default="0 0 0" />
  <xacro:arg name="realsense_rpy" default="0 0 0" />
  <xacro:arg name="realsense_mount" default="sensor_arch_mount_link" />

  <xacro:property name="husky_front_bumper_extend" value="0" />
  <xacro:property name="husky_rear_bumper_extend" value="0" />

  <xacro:arg name="robot_namespace" default="/" />
  <xacro:arg name="is_sim" default="false" />
  <xacro:arg name="urdf_extras" default="empty.urdf" />
  <xacro:arg name="serial_port" default="/dev/prolific" />

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find nav2_bringup)/urdf/beetle/wheel.xacro" />
  <xacro:include filename="$(find nav2_bringup)/urdf/beetle/accessories/intel_realsense.urdf.xacro"/>
  <!-- <xacro:include filename="$(find nav2_bringup)/urdf/beetle/accessories/sick_lms1xx_mount.urdf.xacro"/> -->
  <xacro:include filename="$(find nav2_bringup)/urdf/beetle/accessories/sensor_arch.urdf.xacro"/>

  <xacro:property name="M_PI" value="3.14159"/>

  <xacro:macro name="base" params="prefix">

    <!-- Base Size -->
    <xacro:property name="base_x_size" value="0.98740000" />
    <xacro:property name="base_y_size" value="0.57090000" />
    <xacro:property name="base_z_size" value="0.24750000" />

    <!-- Wheel Mounting Positions -->
    <xacro:property name="wheelbase" value="0.5120" />
    <xacro:property name="track" value="0.5708" />
    <xacro:property name="wheel_vertical_offset" value="0.03282" />

    <!-- Wheel Properties -->
    <xacro:property name="wheel_length" value="0.1143" />
    <xacro:property name="wheel_radius" value="0.1651" />

    <!-- Base link is the center of the robot's bottom plate -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://nav2_bringup/meshes/base_link.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="${( husky_front_bumper_extend - husky_rear_bumper_extend ) / 2.0} 0 ${base_z_size/4}" rpy="0 0 0" />
        <geometry>
          <box size="${ base_x_size + husky_front_bumper_extend + husky_rear_bumper_extend } ${base_y_size} ${base_z_size/2}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 ${base_z_size*3/4-0.01}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size*4/5} ${base_y_size} ${base_z_size/2-0.02}"/>
        </geometry>
      </collision>
    </link>

    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_footprint" />
    </joint>

    <!-- Inertial link stores the robot's inertial information -->
    <link name="inertial_link">
      <inertial>
        <mass value="46.034" />
        <origin xyz="-0.00065 -0.085 0.062" />
        <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>

    <!-- IMU Link-->
    <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="imu_link" />
    </joint>

    <!-- GPS Link-->
    <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
    <link name="gps_link"/>
    <joint name="gps_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="gps_link" />
    </joint>

    <!-- LASER Link-->
    <link name="base_scan">
      <inertial>
        <origin xyz="-0.052 0 0.111" rpy="0 0 0" />
        <inertia ixx="0.001" ixy="0.000" ixz="0.000" iyy="0.001" iyz="0.000" izz="0.001" />
        <mass value="0.125"/>
      </inertial>

      <collision name="lidar_sensor_collision">
        <origin xyz="-0.052 0 0.111" rpy="0 0 0" />
        <geometry>
          <cylinder radius="0.0508" length="0.055" />
        </geometry>
      </collision>

      <visual>
        <origin xyz="-0.064 0 0.35" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://nav2_bringup/meshes/accessories/lms1xx_mount.dae" />
        </geometry>
      </visual>
    </link>
    <joint name="lidar_joint" type="fixed">
      <origin xyz="-0.064 0 0.121" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_scan" />
      <axis xyz="0 0 1" />
    </joint>

    <!-- beetle wheel macros -->
    <xacro:wheel wheel_prefix="front_left">
      <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:wheel>
    <xacro:wheel wheel_prefix="front_right">
      <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:wheel>
    <xacro:wheel wheel_prefix="rear_left">
      <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:wheel>
    <xacro:wheel wheel_prefix="rear_right">
      <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:wheel>

  </xacro:macro>

</robot>
